/**
 * @file error.hpp
 */

#pragma once
#include <stdexcept>

namespace net {
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wweak-vtables"
  /**
   * @brief Reports errors generated by net::socket and its subclasses.
   */
  class socket_error : public std::runtime_error {
    public:
      /**
       * @brief Constructs the `net::socket_error` object.
       * @param[in] what_arg Explanatory string.
       */
      explicit socket_error(std::string const& what_arg) : runtime_error(what_arg) { }

      /**
       * @brief Constructs the `net::socket_error` object.
       * @param[in] what_arg Explanatory string.
       */
      explicit socket_error(char const* what_arg) : runtime_error(what_arg) { }
  };
#pragma clang diagnostic pop
}
